### ISSUE TITLE
Where is the script ?

### ISSUE THREAD

**Issue by PascalBourdier** [jonathanio/monitoring-nagios-haproxy#2]
https://github.com/jonathanio/monitoring-nagios-haproxy/blob/master/check_haproxy contain only doc !

**Comment by jonathanio** [comment]
I'll have to investigate it, but it is there - you will have to click on the RAW link.

The Perl script includes POD documentation and GitHub is now displaying that and not the script itself.

**Comment by PascalBourdier** [comment]
ok sorry for the inconvenience
