### ISSUE TITLE
Disable critical state

### ISSUE THREAD

**Issue by jouir** [jonathanio/monitoring-nagios-haproxy#7]
Hello,

I have an HAProxy backend with several hosts and an other backend as backup so all hosts can be down, there will be a fallback. I would like to return a warn when all hosts are down but not a crit as service is up.

Specifying zero values isn't working as `check_haproxy` uses defaults values:
```
$ ./check_haproxy --default 'C<u,1,1,80,90>' --overrides read-only:u,1,0 stats:x -d
build_checks{} setting defaults to u,1.00,1.00,0.80,0.90
build_checks{} processing override read-only:u,1,0
build_checks{} setting override for read-only to u,1,1,0.80,0.90
```
Lines were removed for readability.

Do you know how to disable critical state for a given backend?

**Comment by jonathanio** [comment]
Again, thanks for the Pull Request. I've now merged it, so I'll close this issue.
